### ISSUE TITLE
FOBI has a lot of broken IRIs which makes it impossible to process

### ISSUE THREAD

**Issue by matentzn** [pcastellanoescuder/FoodBiomarkerOntology#7]
I never noticed this before, but see http://dashboard.obofoundry.org/dashboard/fobi/dashboard.html

Trying to run ROBOT (any command):

```
robot -vvv remove -i fobi.owl --term BFO:0000050 -o test.owl
```

will cause:

```
For details see: http://robot.obolibrary.org/errors#invalid-element-error
java.io.IOException: errors#INVALID ELEMENT ERROR "http://purl.obolibrary.org/obo/fobi.owl#FOBI:050339" contains invalid characters
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1745)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:846)
	at org.obolibrary.robot.CommandLineHelper.maybeSaveOutput(CommandLineHelper.java:667)
	at org.obolibrary.robot.RemoveCommand.execute(RemoveCommand.java:156)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:244)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:188)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:60)
```

Looking in more depth, something about these terms has to be gone wrong:

<details><summary>Bad FOBI IDs</summary>
FOBI:050202
FOBI:050203
FOBI:050204
FOBI:050205
FOBI:050206
FOBI:050207
FOBI:050208
FOBI:050209
FOBI:050210
FOBI:050211
FOBI:050212
FOBI:050213
FOBI:050214
FOBI:050215
FOBI:050216
FOBI:050217
FOBI:050218
FOBI:050219
FOBI:050220
FOBI:050221
FOBI:050222
FOBI:050223
FOBI:050224
FOBI:050225
FOBI:050226
FOBI:050227
FOBI:050228
FOBI:050229
FOBI:050230
FOBI:050231
FOBI:050232
FOBI:050233
FOBI:050234
FOBI:050235
FOBI:050236
FOBI:050237
FOBI:050238
FOBI:050239
FOBI:050240
FOBI:050241
FOBI:050242
FOBI:050243
FOBI:050244
FOBI:050245
FOBI:050246
FOBI:050247
FOBI:050248
FOBI:050249
FOBI:050250
FOBI:050251
FOBI:050252
FOBI:050253
FOBI:050254
FOBI:050255
FOBI:050256
FOBI:050257
FOBI:050258
FOBI:050259
FOBI:050260
FOBI:050261
FOBI:050262
FOBI:050263
FOBI:050264
FOBI:050265
FOBI:050266
FOBI:050267
FOBI:050268
FOBI:050269
FOBI:050270
FOBI:050271
FOBI:050272
FOBI:050273
FOBI:050274
FOBI:050275
FOBI:050276
FOBI:050277
FOBI:050278
FOBI:050279
FOBI:050280
FOBI:050281
FOBI:050282
FOBI:050283
FOBI:050284
FOBI:050285
FOBI:050286
FOBI:050287
FOBI:050288
FOBI:050289
FOBI:050290
FOBI:050291
FOBI:050292
FOBI:050293
FOBI:050294
FOBI:050295
FOBI:050296
FOBI:050297
FOBI:050298
FOBI:050299
FOBI:050300
FOBI:050301
FOBI:050302
FOBI:050303
FOBI:050304
FOBI:050305
FOBI:050306
FOBI:050307
FOBI:050308
FOBI:050309
FOBI:050310
FOBI:050311
FOBI:050312
FOBI:050313
FOBI:050314
FOBI:050315
FOBI:050316
FOBI:050317
FOBI:050318
FOBI:050319
FOBI:050320
FOBI:050321
FOBI:050322
FOBI:050323
FOBI:050324
FOBI:050325
FOBI:050326
FOBI:050327
FOBI:050328
FOBI:050329
FOBI:050330
FOBI:050331
FOBI:050332
FOBI:050333
FOBI:050334
FOBI:050335
FOBI:050336
FOBI:050337
FOBI:050338
FOBI:050339
FOBI:050202
FOBI:050203
FOBI:050204
FOBI:050205
FOBI:050206
FOBI:050207
FOBI:050208
FOBI:050209
FOBI:050210
FOBI:050211
FOBI:050212
FOBI:050213
FOBI:050214
FOBI:050215
FOBI:050216
FOBI:050217
FOBI:050218
FOBI:050219
FOBI:050220
FOBI:050221
FOBI:050222
FOBI:050223
FOBI:050224
FOBI:050225
FOBI:050226
FOBI:050227
FOBI:050228
FOBI:050229
FOBI:050230
FOBI:050231
FOBI:050232
FOBI:050233
FOBI:050234
FOBI:050235
FOBI:050236
FOBI:050237
FOBI:050238
FOBI:050239
FOBI:050240
FOBI:050241
FOBI:050242
FOBI:050243
FOBI:050244
FOBI:050245
FOBI:050246
FOBI:050247
FOBI:050248
FOBI:050249
FOBI:050250
FOBI:050251
FOBI:050252
FOBI:050253
FOBI:050254
FOBI:050255
FOBI:050256
FOBI:050257
FOBI:050258
FOBI:050259
FOBI:050260
FOBI:050261
FOBI:050262
FOBI:050263
FOBI:050264
FOBI:050265
FOBI:050266
FOBI:050267
FOBI:050268
FOBI:050269
FOBI:050270
FOBI:050271
FOBI:050272
FOBI:050273
FOBI:050274
FOBI:050275
FOBI:050276
FOBI:050277
FOBI:050278
FOBI:050279
FOBI:050280
FOBI:050281
FOBI:050282
FOBI:050283
FOBI:050284
FOBI:050285
FOBI:050286
FOBI:050287
FOBI:050288
FOBI:050289
FOBI:050290
FOBI:050291
FOBI:050292
FOBI:050293
FOBI:050294
FOBI:050295
FOBI:050296
FOBI:050297
FOBI:050298
FOBI:050299
FOBI:050300
FOBI:050301
FOBI:050302
FOBI:050303
FOBI:050304
FOBI:050305
FOBI:050306
FOBI:050307
FOBI:050308
FOBI:050309
FOBI:050310
FOBI:050311
FOBI:050312
FOBI:050313
FOBI:050314
FOBI:050315
FOBI:050316
FOBI:050317
FOBI:050318
FOBI:050319
FOBI:050320
FOBI:050321
FOBI:050322
FOBI:050323
FOBI:050324
FOBI:050325
FOBI:050326
FOBI:050327
FOBI:050328
FOBI:050329
FOBI:050330
FOBI:050331
FOBI:050332
FOBI:050333
FOBI:050334
FOBI:050335
FOBI:050336
FOBI:050337
FOBI:050338
FOBI:050339
</details>

**Comment by matentzn** [comment]
In functional syntax this becomes more clear:

<details><summary>Bad FOBI IRIs</summary>
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050001>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050002>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050003>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050004>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050005>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050006>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050007>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050008>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050009>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050010>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050011>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050012>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050013>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050014>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050015>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050016>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050017>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050018>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050019>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050020>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050021>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050022>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050023>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050024>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050025>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050026>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050027>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050028>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050029>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050030>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050031>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050032>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050033>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050034>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050035>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050036>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050037>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050038>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050039>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050040>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050041>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050042>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050043>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050044>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050045>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050046>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050047>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050048>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050049>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050050>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050051>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050052>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050053>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050054>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050055>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050056>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050057>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050058>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050059>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050060>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050061>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050062>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050063>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050064>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050065>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050066>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050067>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050068>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050069>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050070>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050071>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050072>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050073>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050074>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050075>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050076>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050077>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050078>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050079>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050080>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050081>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050082>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050083>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050084>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050085>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050086>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050087>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050088>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050089>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050090>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050091>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050092>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050093>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050094>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050095>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050096>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI_050097>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050202>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050203>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050204>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050205>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050206>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050207>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050208>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050209>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050210>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050211>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050212>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050213>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050214>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050215>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050216>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050217>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050218>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050219>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050220>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050221>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050222>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050223>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050224>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050225>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050226>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050227>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050228>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050229>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050230>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050231>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050232>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050233>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050234>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050235>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050236>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050237>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050238>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050239>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050240>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050241>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050242>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050243>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050244>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050245>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050246>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050247>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050248>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050249>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050250>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050251>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050252>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050253>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050254>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050255>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050256>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050257>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050258>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050259>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050260>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050261>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050262>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050263>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050264>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050265>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050266>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050267>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050268>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050269>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050270>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050271>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050272>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050273>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050274>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050275>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050276>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050277>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050278>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050279>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050280>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050281>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050282>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050283>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050284>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050285>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050286>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050287>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050288>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050289>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050290>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050291>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050292>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050293>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050294>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050295>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050296>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050297>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050298>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050299>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050300>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050301>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050302>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050303>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050304>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050305>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050306>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050307>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050308>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050309>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050310>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050311>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050312>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050313>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050314>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050315>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050316>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050317>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050318>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050319>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050320>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050321>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050322>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050323>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050324>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050325>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050326>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050327>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050328>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050329>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050330>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050331>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050332>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050333>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050334>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050335>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050336>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050337>))
Declaration(Class(<http://purl.obolibrary.org/obo/fobi.owl#FOBI:050338>))
</details>

cc @ddooley

**Comment by ddooley** [comment]
Pol, let me know if you need a hand in resolving this. To match OBOFoundry ID pattern, all FOBI ids should look like: 
http://purl.obolibrary.org/obo/FOBI_050339
rather than:
http://purl.obolibrary.org/obo/fobi.owl#FOBI:050339

**Comment by ddooley** [comment]
it looks like it snuck into your FOBI minted biomarkers branch, about 225 terms:

![image](https://user-images.githubusercontent.com/4000582/153623178-697b6ce6-ae13-461d-86e0-528c082031f9.png)

I think the fix requires two search and replace operations that can be done on the src/ontology/fobi-edit.owl text file I guess, and then regenerate fobi.owl .  Note both FOBI:1234567 and FOBI_1234567 patterns exist

http://purl.obolibrary.org/obo/fobi.owl#FOBI: --> http://purl.obolibrary.org/obo/FOBI_
and
http://purl.obolibrary.org/obo/fobi.owl#FOBI_ --> http://purl.obolibrary.org/obo/FOBI_

**Comment by ddooley** [comment]
I have fixed this annotation in fobi.owl on my computer; just awaiting the ok to upload that to github.

**Comment by pcastellanoescuder** [comment]
Thanks a lot @ddooley. Please, upload the changes to GitHub when it's OK for you. It's definitely OK for me:)

**Comment by ddooley** [comment]
Fix uploaded.  Hopefully that helps get it into the OBO Foundry control panel stats.

**Comment by pcastellanoescuder** [comment]
Thank you so much @ddooley!
